# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rest.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', rest.models.KeyField(max_length=52, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=256)),
                ('invited_by', rest.models.KeyField(max_length=52)),
                ('payload', models.CharField(max_length=1024)),
                ('invitee_signature', rest.models.SignatureField(max_length=256)),
                ('user_signature', rest.models.SignatureField(max_length=256)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Group')),
            ],
        ),
    ]
